spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/smatech_auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Africa/Harare
    url: jdbc:mysql://host.docker.internal:3306/smartech_ecommerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Africa/Harare
    username: smatech
    password: smatech@2025
notification:
  url: http://localhost:6800/api/notifications/email/send